import { Overpass } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const overpass = Overpass({
  variable: "--font-overpass",
  subsets: ["latin"],
});

export const metadata = {
  title: "2DREALM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${overpass.variable} font-overpass antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
